app:
  name: "Audio File Management App"
  debug: true
  secret_key: "dev-secret-key-change-in-production"
  host: "0.0.0.0"
  port: 5000

database:
  postgres:
    host: "postgres"
    port: 5432
    database: "audioapp"
    username: "audioapp_user"
    password: "audioapp_password"

  mongodb:
    host: "mongodb"
    port: 27017
    database: "audioapp"
    username: "audioapp_user"
    password: "audioapp_password"

security:
  password_min_length: 8
  session_timeout_minutes: 60

file_upload:
  max_file_size_mb: 50
  allowed_extensions:
    - "mp3"
    - "wav"
    - "ogg"
    - "m4a"
    - "flac"
